// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntqfsdghszgjkzfpcaol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50cWZzZGdoc3pnamt6ZnBjYW9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MDMzMjcsImV4cCI6MjA3NDI3OTMyN30.9ddPbfKD-FCjUnKc2_svxD7EgB6uJGUfCVoyhR3iLmU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});